/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface InterestRateModelInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "WAD"
      | "YEAR_IN_SECONDS"
      | "baseRate"
      | "getBorrowRate"
      | "getSupplyRate"
      | "kink"
      | "reserveFactor"
      | "slope1"
      | "slope2"
      | "utilizationRate"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "WAD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "YEAR_IN_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "baseRate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBorrowRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupplyRate",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "kink", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reserveFactor",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "slope1", values?: undefined): string;
  encodeFunctionData(functionFragment: "slope2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "utilizationRate",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "WAD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "YEAR_IN_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "baseRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupplyRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kink", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reserveFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "slope1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "slope2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "utilizationRate",
    data: BytesLike
  ): Result;
}

export interface InterestRateModel extends BaseContract {
  connect(runner?: ContractRunner | null): InterestRateModel;
  waitForDeployment(): Promise<this>;

  interface: InterestRateModelInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  WAD: TypedContractMethod<[], [bigint], "view">;

  YEAR_IN_SECONDS: TypedContractMethod<[], [bigint], "view">;

  baseRate: TypedContractMethod<[], [bigint], "view">;

  getBorrowRate: TypedContractMethod<[util: BigNumberish], [bigint], "view">;

  getSupplyRate: TypedContractMethod<
    [util: BigNumberish, borrowRate: BigNumberish],
    [bigint],
    "view"
  >;

  kink: TypedContractMethod<[], [bigint], "view">;

  reserveFactor: TypedContractMethod<[], [bigint], "view">;

  slope1: TypedContractMethod<[], [bigint], "view">;

  slope2: TypedContractMethod<[], [bigint], "view">;

  utilizationRate: TypedContractMethod<
    [totalLiquidity: BigNumberish, totalDebt: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "WAD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "YEAR_IN_SECONDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "baseRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBorrowRate"
  ): TypedContractMethod<[util: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSupplyRate"
  ): TypedContractMethod<
    [util: BigNumberish, borrowRate: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "kink"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserveFactor"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "slope1"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "slope2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "utilizationRate"
  ): TypedContractMethod<
    [totalLiquidity: BigNumberish, totalDebt: BigNumberish],
    [bigint],
    "view"
  >;

  filters: {};
}
