/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface LiquidatorInterface extends Interface {
  getFunction(
    nameOrSignature: "batchLiquidate" | "liquidate"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "LiquidationExecuted"): EventFragment;

  encodeFunctionData(
    functionFragment: "batchLiquidate",
    values: [AddressLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchLiquidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
}

export namespace LiquidationExecutedEvent {
  export type InputTuple = [
    pool: AddressLike,
    borrower: AddressLike,
    debtRepaid: BigNumberish,
    collateralSeized: BigNumberish,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    pool: string,
    borrower: string,
    debtRepaid: bigint,
    collateralSeized: bigint,
    reward: bigint
  ];
  export interface OutputObject {
    pool: string;
    borrower: string;
    debtRepaid: bigint;
    collateralSeized: bigint;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Liquidator extends BaseContract {
  connect(runner?: ContractRunner | null): Liquidator;
  waitForDeployment(): Promise<this>;

  interface: LiquidatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchLiquidate: TypedContractMethod<
    [pools: AddressLike[], borrowers: AddressLike[]],
    [void],
    "nonpayable"
  >;

  liquidate: TypedContractMethod<
    [pool: AddressLike, borrower: AddressLike],
    [
      [bigint, bigint, bigint] & {
        debtRepaid: bigint;
        collateralSeized: bigint;
        reward: bigint;
      }
    ],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchLiquidate"
  ): TypedContractMethod<
    [pools: AddressLike[], borrowers: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "liquidate"
  ): TypedContractMethod<
    [pool: AddressLike, borrower: AddressLike],
    [
      [bigint, bigint, bigint] & {
        debtRepaid: bigint;
        collateralSeized: bigint;
        reward: bigint;
      }
    ],
    "nonpayable"
  >;

  getEvent(
    key: "LiquidationExecuted"
  ): TypedContractEvent<
    LiquidationExecutedEvent.InputTuple,
    LiquidationExecutedEvent.OutputTuple,
    LiquidationExecutedEvent.OutputObject
  >;

  filters: {
    "LiquidationExecuted(address,address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidationExecutedEvent.InputTuple,
      LiquidationExecutedEvent.OutputTuple,
      LiquidationExecutedEvent.OutputObject
    >;
    LiquidationExecuted: TypedContractEvent<
      LiquidationExecutedEvent.InputTuple,
      LiquidationExecutedEvent.OutputTuple,
      LiquidationExecutedEvent.OutputObject
    >;
  };
}
