/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as chainlinkOracleSol from "./ChainlinkOracle.sol";
export { PriceOracleAggregator__factory } from "./PriceOracleAggregator__factory";
