/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ILiquidatorInterface extends Interface {
  getFunction(
    nameOrSignature: "calculateLiquidationAmount" | "liquidate"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculateLiquidationAmount",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateLiquidationAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
}

export interface ILiquidator extends BaseContract {
  connect(runner?: ContractRunner | null): ILiquidator;
  waitForDeployment(): Promise<this>;

  interface: ILiquidatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateLiquidationAmount: TypedContractMethod<
    [pool: AddressLike, borrower: AddressLike],
    [
      [bigint, bigint, bigint] & {
        maxDebtToRepay: bigint;
        collateralToSeize: bigint;
        reward: bigint;
      }
    ],
    "view"
  >;

  liquidate: TypedContractMethod<
    [pool: AddressLike, borrower: AddressLike],
    [
      [bigint, bigint, bigint] & {
        debtRepaid: bigint;
        collateralSeized: bigint;
        reward: bigint;
      }
    ],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateLiquidationAmount"
  ): TypedContractMethod<
    [pool: AddressLike, borrower: AddressLike],
    [
      [bigint, bigint, bigint] & {
        maxDebtToRepay: bigint;
        collateralToSeize: bigint;
        reward: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "liquidate"
  ): TypedContractMethod<
    [pool: AddressLike, borrower: AddressLike],
    [
      [bigint, bigint, bigint] & {
        debtRepaid: bigint;
        collateralSeized: bigint;
        reward: bigint;
      }
    ],
    "nonpayable"
  >;

  filters: {};
}
