/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGovernance } from "./IGovernance";
export type { IInterestRateModel } from "./IInterestRateModel";
export type { ILiquidator } from "./ILiquidator";
export type { IOracle } from "./IOracle";
export type { IPool } from "./IPool";
export type { IRToken } from "./IRToken";
