/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IOracleInterface extends Interface {
  getFunction(
    nameOrSignature: "getPrice" | "isTrustedSource"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PriceUpdated" | "SourceAdded" | "SourceRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getPrice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedSource",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedSource",
    data: BytesLike
  ): Result;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [
    asset: AddressLike,
    price: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [asset: string, price: bigint, timestamp: bigint];
  export interface OutputObject {
    asset: string;
    price: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SourceAddedEvent {
  export type InputTuple = [source: AddressLike];
  export type OutputTuple = [source: string];
  export interface OutputObject {
    source: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SourceRemovedEvent {
  export type InputTuple = [source: AddressLike];
  export type OutputTuple = [source: string];
  export interface OutputObject {
    source: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IOracle;
  waitForDeployment(): Promise<this>;

  interface: IOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPrice: TypedContractMethod<
    [asset: AddressLike],
    [[bigint, bigint] & { price: bigint; decimals: bigint }],
    "view"
  >;

  isTrustedSource: TypedContractMethod<
    [source: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<
    [asset: AddressLike],
    [[bigint, bigint] & { price: bigint; decimals: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTrustedSource"
  ): TypedContractMethod<[source: AddressLike], [boolean], "view">;

  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SourceAdded"
  ): TypedContractEvent<
    SourceAddedEvent.InputTuple,
    SourceAddedEvent.OutputTuple,
    SourceAddedEvent.OutputObject
  >;
  getEvent(
    key: "SourceRemoved"
  ): TypedContractEvent<
    SourceRemovedEvent.InputTuple,
    SourceRemovedEvent.OutputTuple,
    SourceRemovedEvent.OutputObject
  >;

  filters: {
    "PriceUpdated(address,uint256,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "SourceAdded(address)": TypedContractEvent<
      SourceAddedEvent.InputTuple,
      SourceAddedEvent.OutputTuple,
      SourceAddedEvent.OutputObject
    >;
    SourceAdded: TypedContractEvent<
      SourceAddedEvent.InputTuple,
      SourceAddedEvent.OutputTuple,
      SourceAddedEvent.OutputObject
    >;

    "SourceRemoved(address)": TypedContractEvent<
      SourceRemovedEvent.InputTuple,
      SourceRemovedEvent.OutputTuple,
      SourceRemovedEvent.OutputObject
    >;
    SourceRemoved: TypedContractEvent<
      SourceRemovedEvent.InputTuple,
      SourceRemovedEvent.OutputTuple,
      SourceRemovedEvent.OutputObject
    >;
  };
}
