/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "borrow"
      | "collateralAsset"
      | "deposit"
      | "depositAsset"
      | "getBorrowRate"
      | "getHealthFactor"
      | "getSupplyRate"
      | "getUtilizationRate"
      | "liquidate"
      | "liquidationBonus"
      | "liquidationThreshold"
      | "minCollateralRatio"
      | "rToken"
      | "repay"
      | "totalDebt"
      | "totalLiquidity"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Borrowed"
      | "Deposited"
      | "InterestRateUpdated"
      | "Liquidated"
      | "Repaid"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "borrow",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralAsset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositAsset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHealthFactor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupplyRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUtilizationRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationBonus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minCollateralRatio",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "rToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "totalDebt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collateralAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHealthFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupplyRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUtilizationRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidationBonus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minCollateralRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalDebt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace BorrowedEvent {
  export type InputTuple = [
    borrower: AddressLike,
    amount: BigNumberish,
    debtShares: BigNumberish
  ];
  export type OutputTuple = [
    borrower: string,
    amount: bigint,
    debtShares: bigint
  ];
  export interface OutputObject {
    borrower: string;
    amount: bigint;
    debtShares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    lender: AddressLike,
    amount: BigNumberish,
    rTokensMinted: BigNumberish
  ];
  export type OutputTuple = [
    lender: string,
    amount: bigint,
    rTokensMinted: bigint
  ];
  export interface OutputObject {
    lender: string;
    amount: bigint;
    rTokensMinted: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InterestRateUpdatedEvent {
  export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish];
  export type OutputTuple = [oldRate: bigint, newRate: bigint];
  export interface OutputObject {
    oldRate: bigint;
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidatedEvent {
  export type InputTuple = [
    liquidator: AddressLike,
    borrower: AddressLike,
    debtRepaid: BigNumberish,
    collateralSeized: BigNumberish,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    liquidator: string,
    borrower: string,
    debtRepaid: bigint,
    collateralSeized: bigint,
    reward: bigint
  ];
  export interface OutputObject {
    liquidator: string;
    borrower: string;
    debtRepaid: bigint;
    collateralSeized: bigint;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepaidEvent {
  export type InputTuple = [
    borrower: AddressLike,
    amount: BigNumberish,
    debtSharesBurned: BigNumberish
  ];
  export type OutputTuple = [
    borrower: string,
    amount: bigint,
    debtSharesBurned: bigint
  ];
  export interface OutputObject {
    borrower: string;
    amount: bigint;
    debtSharesBurned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    lender: AddressLike,
    amount: BigNumberish,
    rTokensBurned: BigNumberish
  ];
  export type OutputTuple = [
    lender: string,
    amount: bigint,
    rTokensBurned: bigint
  ];
  export interface OutputObject {
    lender: string;
    amount: bigint;
    rTokensBurned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPool extends BaseContract {
  connect(runner?: ContractRunner | null): IPool;
  waitForDeployment(): Promise<this>;

  interface: IPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  borrow: TypedContractMethod<
    [amount: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  collateralAsset: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<
    [amount: BigNumberish, onBehalfOf: AddressLike],
    [bigint],
    "nonpayable"
  >;

  depositAsset: TypedContractMethod<[], [string], "view">;

  getBorrowRate: TypedContractMethod<[], [bigint], "view">;

  getHealthFactor: TypedContractMethod<
    [borrower: AddressLike],
    [bigint],
    "view"
  >;

  getSupplyRate: TypedContractMethod<[], [bigint], "view">;

  getUtilizationRate: TypedContractMethod<[], [bigint], "view">;

  liquidate: TypedContractMethod<
    [borrower: AddressLike],
    [
      [bigint, bigint, bigint] & {
        debtRepaid: bigint;
        collateralSeized: bigint;
        reward: bigint;
      }
    ],
    "nonpayable"
  >;

  liquidationBonus: TypedContractMethod<[], [bigint], "view">;

  liquidationThreshold: TypedContractMethod<[], [bigint], "view">;

  minCollateralRatio: TypedContractMethod<[], [bigint], "view">;

  rToken: TypedContractMethod<[], [string], "view">;

  repay: TypedContractMethod<
    [amount: BigNumberish, onBehalfOf: AddressLike],
    [bigint],
    "nonpayable"
  >;

  totalDebt: TypedContractMethod<[], [bigint], "view">;

  totalLiquidity: TypedContractMethod<[], [bigint], "view">;

  withdraw: TypedContractMethod<
    [rTokenAmount: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "borrow"
  ): TypedContractMethod<
    [amount: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "collateralAsset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [amount: BigNumberish, onBehalfOf: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositAsset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBorrowRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHealthFactor"
  ): TypedContractMethod<[borrower: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSupplyRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUtilizationRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidate"
  ): TypedContractMethod<
    [borrower: AddressLike],
    [
      [bigint, bigint, bigint] & {
        debtRepaid: bigint;
        collateralSeized: bigint;
        reward: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "liquidationBonus"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidationThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minCollateralRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<
    [amount: BigNumberish, onBehalfOf: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalDebt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalLiquidity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [rTokenAmount: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "Borrowed"
  ): TypedContractEvent<
    BorrowedEvent.InputTuple,
    BorrowedEvent.OutputTuple,
    BorrowedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "InterestRateUpdated"
  ): TypedContractEvent<
    InterestRateUpdatedEvent.InputTuple,
    InterestRateUpdatedEvent.OutputTuple,
    InterestRateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Liquidated"
  ): TypedContractEvent<
    LiquidatedEvent.InputTuple,
    LiquidatedEvent.OutputTuple,
    LiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "Repaid"
  ): TypedContractEvent<
    RepaidEvent.InputTuple,
    RepaidEvent.OutputTuple,
    RepaidEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Borrowed(address,uint256,uint256)": TypedContractEvent<
      BorrowedEvent.InputTuple,
      BorrowedEvent.OutputTuple,
      BorrowedEvent.OutputObject
    >;
    Borrowed: TypedContractEvent<
      BorrowedEvent.InputTuple,
      BorrowedEvent.OutputTuple,
      BorrowedEvent.OutputObject
    >;

    "Deposited(address,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "InterestRateUpdated(uint256,uint256)": TypedContractEvent<
      InterestRateUpdatedEvent.InputTuple,
      InterestRateUpdatedEvent.OutputTuple,
      InterestRateUpdatedEvent.OutputObject
    >;
    InterestRateUpdated: TypedContractEvent<
      InterestRateUpdatedEvent.InputTuple,
      InterestRateUpdatedEvent.OutputTuple,
      InterestRateUpdatedEvent.OutputObject
    >;

    "Liquidated(address,address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidatedEvent.InputTuple,
      LiquidatedEvent.OutputTuple,
      LiquidatedEvent.OutputObject
    >;
    Liquidated: TypedContractEvent<
      LiquidatedEvent.InputTuple,
      LiquidatedEvent.OutputTuple,
      LiquidatedEvent.OutputObject
    >;

    "Repaid(address,uint256,uint256)": TypedContractEvent<
      RepaidEvent.InputTuple,
      RepaidEvent.OutputTuple,
      RepaidEvent.OutputObject
    >;
    Repaid: TypedContractEvent<
      RepaidEvent.InputTuple,
      RepaidEvent.OutputTuple,
      RepaidEvent.OutputObject
    >;

    "Withdrawn(address,uint256,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
