/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  InterestRateModel,
  InterestRateModelInterface,
} from "../../../src/interest/InterestRateModel";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_baseRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_kink",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_slope1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_slope2",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_reserveFactor",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "WAD",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "YEAR_IN_SECONDS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "baseRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "util",
        type: "uint256",
      },
    ],
    name: "getBorrowRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "util",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "borrowRate",
        type: "uint256",
      },
    ],
    name: "getSupplyRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "kink",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "reserveFactor",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "slope1",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "slope2",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "totalLiquidity",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalDebt",
        type: "uint256",
      },
    ],
    name: "utilizationRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60803461007457601f61038a38819003918201601f19168301916001600160401b038311848410176100785780849260a09460405283398101031261007457805190602081015160408201519060806060840151930151935f556001556002556003556004556040516102fd908161008d8239f35b5f80fd5b634e487b7160e01b5f52604160045260245ffdfe60806040908082526004361015610014575f80fd5b5f3560e01c9081631f68f20a146101e6575080632a11a8a0146101895780634322b7141461016b5780636a146024146101495780637847ea531461012b5780639fa83b5a1461010b578063a62b75a8146100ed578063d0134cb7146100cf578063ec2de40c146100ad5763fd2da3391461008c575f80fd5b346100a9575f3660031901126100a9576020906001549051908152f35b5f80fd5b50346100a9576020906100c86100c2366101ff565b9061029c565b9051908152f35b50346100a9575f3660031901126100a9576020906003549051908152f35b50346100a9575f3660031901126100a9576020906002549051908152f35b50346100a95760203660031901126100a9576020906100c8600435610235565b50346100a9575f3660031901126100a957602090516301e133808152f35b50346100a9575f3660031901126100a95760209051670de0b6b3a76400008152f35b50346100a9575f3660031901126100a9576020906004549051908152f35b50346100a957610198366101ff565b60049291925490670de0b6b3a7640000918203938285116101d257826101c36020966101ca94610215565b0490610215565b049051908152f35b634e487b7160e01b5f52601160045260245ffd5b346100a9575f3660031901126100a9576020905f548152f35b60409060031901126100a9576004359060243590565b818102929181159184041417156101d257565b919082018092116101d257565b600154808211610266575061026390670de0b6b3a764000061025c5f549260025490610215565b0490610228565b90565b5f54610282670de0b6b3a7640000918261025c60025486610215565b9183039283116101d25761025c6102639360035490610215565b9081156102c157670de0b6b3a7640000908181029181830414901517156101d2570490565b50505f9056fea2646970667358221220d81e3877f9e5b3129cf9a62bef0e5d82abdfa9237979bcf26dc7e597a81372ba64736f6c63430008180033";

type InterestRateModelConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: InterestRateModelConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class InterestRateModel__factory extends ContractFactory {
  constructor(...args: InterestRateModelConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _baseRate: BigNumberish,
    _kink: BigNumberish,
    _slope1: BigNumberish,
    _slope2: BigNumberish,
    _reserveFactor: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      _baseRate,
      _kink,
      _slope1,
      _slope2,
      _reserveFactor,
      overrides || {}
    );
  }
  override deploy(
    _baseRate: BigNumberish,
    _kink: BigNumberish,
    _slope1: BigNumberish,
    _slope2: BigNumberish,
    _reserveFactor: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(
      _baseRate,
      _kink,
      _slope1,
      _slope2,
      _reserveFactor,
      overrides || {}
    ) as Promise<
      InterestRateModel & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): InterestRateModel__factory {
    return super.connect(runner) as InterestRateModel__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): InterestRateModelInterface {
    return new Interface(_abi) as InterestRateModelInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): InterestRateModel {
    return new Contract(address, _abi, runner) as unknown as InterestRateModel;
  }
}
