/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IInterestRateModel,
  IInterestRateModelInterface,
} from "../../../src/interfaces/IInterestRateModel";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "utilizationRate",
        type: "uint256",
      },
    ],
    name: "getBorrowRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "utilizationRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "borrowRate",
        type: "uint256",
      },
    ],
    name: "getSupplyRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "totalLiquidity",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalDebt",
        type: "uint256",
      },
    ],
    name: "utilizationRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IInterestRateModel__factory {
  static readonly abi = _abi;
  static createInterface(): IInterestRateModelInterface {
    return new Interface(_abi) as IInterestRateModelInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IInterestRateModel {
    return new Contract(address, _abi, runner) as unknown as IInterestRateModel;
  }
}
