/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILiquidator,
  ILiquidatorInterface,
} from "../../../src/interfaces/ILiquidator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        internalType: "address",
        name: "borrower",
        type: "address",
      },
    ],
    name: "calculateLiquidationAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "maxDebtToRepay",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "collateralToSeize",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "reward",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        internalType: "address",
        name: "borrower",
        type: "address",
      },
    ],
    name: "liquidate",
    outputs: [
      {
        internalType: "uint256",
        name: "debtRepaid",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "collateralSeized",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "reward",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILiquidator__factory {
  static readonly abi = _abi;
  static createInterface(): ILiquidatorInterface {
    return new Interface(_abi) as ILiquidatorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ILiquidator {
    return new Contract(address, _abi, runner) as unknown as ILiquidator;
  }
}
