/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGovernance__factory } from "./IGovernance__factory";
export { IInterestRateModel__factory } from "./IInterestRateModel__factory";
export { ILiquidator__factory } from "./ILiquidator__factory";
export { IOracle__factory } from "./IOracle__factory";
export { IPool__factory } from "./IPool__factory";
export { IRToken__factory } from "./IRToken__factory";
